meta_product_name: "Mhisto"
meta_title: "Mhisto: à toi d'écrire l'histoire"
meta_description: "Mhisto te permet de remplir des challenges d'écriture. Chaque semaine, fais un nouveau challenge et améliore ton style d'écriture. Commence à écrire entre les lignes."
meta_image: "mhistopage.jpg"
twitter_account: "@guilmoute"
